
---

- hosts: all
  gather_facts: yes
  become: true
  tasks:

  - name: update repository index
    yum:
      update_cache: yes

  - name: install apache2 package
    yum:
      name: httpd
      state: latest
  
  - name: install support for php
    yum:
      name: php
      state: latest
