
---

- hosts: all
  gather_facts: yes
  become: true
  tasks:

  - name: update repository index
    yum:
      update_cache: yes

    when: ansible_distribution == "CentOS"
  - name: install apache2 package
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"
  - name: install support for php
    yum:
      name: php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: update repository index
    apt:
      update_cache: yes

    when: ansible_distribution == "Ubuntu"
  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"
  - name: install support for php
    apt:
      name: php
      state: latest
    when: ansible_distribution == "Ubuntu"
