
---

- hosts: all
  gather_facts: yes
  become: true
  tasks:


  - name: install apache2 package
    yum:
      name: 
        - httpd
        - php  
      state: latest
      update_cache: yes  
    when: ansible_distribution == "CentOS"

  - name: install apache2 package
    apt:
      name: 
        - apache2
        - php  
      state: latest
      update_cache: yes  
    when: ansible_distribution == "Ubuntu"
